development:
  adapter: postgresql
  username: postgres
  password: 123
  database: postgre_taici

test:
  adapter: postgresql
  username: postgres
  password: 123
  database: postgre_taici

production:
  adapter: mysql
  encoding: utf8
  database: taici_mysql_db
  pool: 5
  username: root
  password: fishgyuyi177
  host: localhost
